subject = "Структуры данных и алгоритмы"
description = "Материалы для подготовки к экзамену"
term = 4
authors = ["Данила Григорьев"]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
    "Определение алгоритма. Свойства алгоритмов (пять основных свойств: дискретность, детерминированность, понятность, массовость, результативность). Причины возникновения формального определения алгоритма. Основные типы алгоритмических моделей (перечислить).",
    "Машина Поста. Описание, примеры. Тезис Поста. ",
    "Машина Тьюринга. Описание, способы задания (список команд, таблица переходов, граф переходов). Конфигурации МТ. Вычислимость по Тьюрингу. ",
    "Введение в теорию рекурсивных функций. Простейшие функции. Оператор суперпозиции. Оператор примитивной рекурсии. Оператор минимизации. Примитивно-рекурсивные и частично-рекурсивные функции. Тезис Черча. Примеры и способы задания рекурсивных функций.",
    "Нормальные алгоритмы Маркова.",
    "Алгоритмически неразрешимые задачи. Примеры алгоритмически неразрешимых задач. Методы доказательства алгоритмической неразрешимости. Проблема останова МТ и самоприменимости (доказательство неразрешимости). ",
    "Трудоемкость алгоритма. Функция трудоемкости. Классификация алгоритмов по виду функции трудоемкости.",
    "Асимптотический анализ сложности алгоритмов; сравнение наилучших, средних и наихудших оценок; O-, o-, ω- и θ-нотации. Свойства.",
    "Порядок роста. Основные классы эффективности.",
    "Класс NP. Проблема равенства P и NP. Класс NPС.",
    "Анализ нерекурсивных алгоритмов по фактическому количеству элементарных операций. Анализ трудоемкости основных алгоритмических конструкций.",
    "Оценивание порядков роста времени работы нерекурсивных алгоритмов. Правило суммы и произведения. Оценка основных алгоритмических конструкций.",
    "Анализ рекурсивных алгоритмов. Рекуррентные соотношения. Метод индукции. Метод подстановки.",
    "Анализ рекурсивных алгоритмов. Рекуррентные соотношения. Первая основная теорема. Следствие.",
    "Математический анализ рекурсивных алгоритмов. Рекуррентные соотношения. Вторая основная теорема. Следствия.",
    "Математический анализ рекурсивных алгоритмов. Анализ дерева рекурсии.",
    "Эмпирический анализ алгоритмов.",
    "Основные методы построения алгоритмов. Алгоритмы «Разделяй и властвуй». Примеры.",
    "Основные методы построения алгоритмов. «Жадные» алгоритмы. Примеры.",
    "Основные методы построения алгоритмов. Полный перебор. Поиск с возвратом. Примеры.",
    "Основные методы построения алгоритмов. Метод «ветвей и границ». Примеры.",
    "Основные методы построения алгоритмов. Метод динамического программирования. Примеры.",
    "Алгоритмы «разделяй и властвуй». Быстрая сортировка. Сортировка слиянием. Оценка сложности. Особенности использования.",
    "Алгоритмы сортировок без сравнения элементов. Сортировка подсчетом. Оценка сложности. Особенности использования.",
    "Алгоритмы сортировок без сравнения элементов. Поразрядная сортировка. Оценка сложности. Особенности использования.",
    "Сортировки, работающие за квадратичное время.",
    "Сортировка Шелла. Оценка сложности. Особенности использования.",
    "Пирамидальная сортировка. Оценка сложности. Особенности использования.",
    "Динамическое программирование. Алгоритм Флойда для нахождения кратчайших расстояний между всеми вершинами взвешенного графа. Оценка сложности. Особенности использования.",
    "Двоичное дерево поиска.",
    "Красно-черные деревья. Повороты. Вставка элемента в дерево. Удаление элемента из дерева.",
    "Сбалансированное по высоте дерево поиска (АВЛ – дерево). Повороты. Вставка элемента в дерево. Удаление элемента из дерева.",
    "Поиск подстроки в строке. Алгоритм Кнута - Морриса – Пратта.",
    "Поиск подстроки в строке. Алгоритм Бойера – Мура."
]
